const fs = require('fs');

const filePath = 'backend/src/initial_db.ts';
let content = fs.readFileSync(filePath, 'utf-8');

// Find all matches for views: number,
const regex = /views:\s*(\d+)(,?)/g;
content = content.replace(regex, (match, views, comma) => {
    // Generate a basic SEO description
    return `views: ${views},\n    seoDescription: "In-depth healthcare updates, clinical insights, and policy changes tailored for medical professionals.",\n    keywords: ["healthcare", "medical", "news", "clinical updates", "health policy"]${comma ? ',' : ''}`;
});

// Since we are also adding 10 news for providers, let's append them to the initialArticles array.
const newArticles = `
  {
    id: "prov-001",
    slug: "apollo-hospitals-launches-ai-driven-diagnostics",
    headline: "Corporate Hospitals Launch AI-Driven Diagnostic Centers Across Tier 2 Cities",
    subhead: "Expanding access to advanced healthcare with artificial intelligence.",
    category: "Providers",
    specialties: ["Diagnostics", "Health Tech", "Hospital Operations"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-25T09:00:00Z",
    sourcePublishedAt: "2026-07-24T11:30:00Z",
    readingTimeMinutes: 5,
    status: "published",
    sourceName: "HealicWire Health Network",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.PRESS_RELEASE,
    isAiAssisted: true,
    summary30s: "Major corporate hospitals are expanding AI diagnostics to Tier 2 cities in India.",
    summary2min: "In a massive push for accessible healthcare, corporate hospitals are setting up advanced diagnostic centers powered by AI across Tier 2 cities. These centers will offer rapid screening for cardiovascular and oncological conditions.",
    bodyAnalysis: "### Expansion Strategy\\nThe focus is bridging the urban-rural healthcare divide...\\n\\n### Technology\\nAI tools analyze X-rays and MRIs with 99% accuracy...",
    whyThisMatters: {
      clinicians: "Provides quicker diagnostic turnarounds.",
      students: "Highlights the integration of tech in medicine.",
      hospitalAdministrators: "A new model for operational scalability.",
      patients: "Reduces need to travel to metro cities for diagnosis.",
      researchers: "Provides massive datasets for AI training."
    },
    impactScores: {
      clinicalPractice: 4,
      medicalEducation: 3,
      research: 5,
      publicHealth: 4,
      hospitalOperations: 5,
      patientCare: 5
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "Directly impacts Indian healthcare delivery."
    },
    peerReviewed: false,
    fundingSource: "Private Equity",
    coiNote: "None",
    references: [],
    views: 1250,
    seoDescription: "Corporate hospitals launch AI-driven diagnostic centers across Tier 2 cities in India, improving healthcare access.",
    keywords: ["Corporate Hospitals", "AI Diagnostics", "Tier 2 Cities", "Indian Healthcare", "Health Tech"]
  },
  {
    id: "prov-002",
    slug: "government-medical-colleges-seat-increase-2026",
    headline: "Government Medical Colleges See 15% Increase in Postgraduate Seats",
    subhead: "NMC approves widespread capacity expansion to address specialist shortages.",
    category: "Providers",
    specialties: ["Medical Education", "Policy"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-24T09:00:00Z",
    sourcePublishedAt: "2026-07-23T11:30:00Z",
    readingTimeMinutes: 4,
    status: "published",
    sourceName: "National Medical Commission",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.GOVERNMENT_NOTIFICATION,
    isAiAssisted: false,
    summary30s: "NMC has approved a 15% increase in PG medical seats across government colleges.",
    summary2min: "To combat the acute shortage of specialist doctors in rural areas, the National Medical Commission (NMC) has approved a massive 15% hike in postgraduate seats across state and central government medical colleges for the 2026-27 academic year.",
    bodyAnalysis: "### Capacity Building\\nThe move adds over 5000 new PG seats...\\n\\n### Infrastructure Challenges\\nConcerns remain regarding faculty-to-student ratios...",
    whyThisMatters: {
      clinicians: "More opportunities for specialization.",
      students: "Higher chances of securing PG seats.",
      hospitalAdministrators: "Increased resident workforce.",
      patients: "Eventual increase in specialist availability.",
      researchers: "More postgraduate research output."
    },
    impactScores: {
      clinicalPractice: 3,
      medicalEducation: 5,
      research: 3,
      publicHealth: 4,
      hospitalOperations: 4,
      patientCare: 4
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "Applies directly to Indian medical education system."
    },
    peerReviewed: false,
    fundingSource: "MoHFW",
    coiNote: "None",
    references: [],
    views: 3400,
    seoDescription: "National Medical Commission approves 15% increase in postgraduate seats in Government Medical Colleges in India.",
    keywords: ["Government Medical Colleges", "PG Seats", "NMC", "Medical Education", "India"]
  },
  {
    id: "prov-003",
    slug: "phc-digital-health-records-integration",
    headline: "Primary Health Centres Fully Integrated with ABHA Digital Health Records",
    subhead: "A massive milestone in the Ayushman Bharat Digital Mission.",
    category: "Providers",
    specialties: ["Public Health", "Health Tech"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-23T09:00:00Z",
    sourcePublishedAt: "2026-07-22T11:30:00Z",
    readingTimeMinutes: 6,
    status: "published",
    sourceName: "Ministry of Health",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.GOVERNMENT_NOTIFICATION,
    isAiAssisted: true,
    summary30s: "Over 90% of Primary Health Centres (PHCs) in India are now fully integrated with the ABHA health record system.",
    summary2min: "The Ayushman Bharat Digital Mission has reached a critical milestone, successfully linking over 90% of rural Primary Health Centres (PHCs) to the ABHA digital ecosystem. This allows seamless electronic health record transfers from rural clinics to district hospitals.",
    bodyAnalysis: "### Seamless Transfers\\nPatients referred from PHCs to CHCs or District Hospitals no longer need physical files.\\n\\n### Connectivity Issues\\nInternet reliability in remote areas remains a hurdle.",
    whyThisMatters: {
      clinicians: "Instant access to patient history.",
      students: "Demonstrates implementation of digital health.",
      hospitalAdministrators: "Streamlines referral management.",
      patients: "No need to carry physical files.",
      researchers: "Provides massive anonymized epidemiological data."
    },
    impactScores: {
      clinicalPractice: 4,
      medicalEducation: 2,
      research: 4,
      publicHealth: 5,
      hospitalOperations: 5,
      patientCare: 5
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "Core Indian public health initiative."
    },
    peerReviewed: false,
    fundingSource: "Government of India",
    coiNote: "None",
    references: [],
    views: 2100,
    seoDescription: "Primary Health Centres in India fully integrate with ABHA Digital Health Records for seamless patient care.",
    keywords: ["PHC", "ABHA", "Digital Health", "Public Health", "Ayushman Bharat"]
  },
  {
    id: "prov-004",
    slug: "private-clinics-telemedicine-guidelines-update",
    headline: "Private Clinics Adopt New Telemedicine Protocols for Chronic Care",
    subhead: "Ensuring compliance and improving patient follow-up rates.",
    category: "Providers",
    specialties: ["General Medicine", "Policy"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-22T09:00:00Z",
    sourcePublishedAt: "2026-07-21T11:30:00Z",
    readingTimeMinutes: 5,
    status: "published",
    sourceName: "Indian Medical Association",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.CLINICAL_GUIDELINE,
    isAiAssisted: true,
    summary30s: "New guidelines streamline telemedicine practices for private practitioners managing chronic diseases.",
    summary2min: "Private clinics across the nation are adopting updated telemedicine protocols issued by the IMA. The new rules clarify prescription norms for chronic diseases like diabetes and hypertension via video consultations.",
    bodyAnalysis: "### Updated Prescription Norms\\nSchedule H drugs have stricter video-verification requirements.\\n\\n### Follow-up Compliance\\nClinics report a 40% increase in patient follow-up compliance.",
    whyThisMatters: {
      clinicians: "Protects against medico-legal risks.",
      students: "Important for medical ethics and practice management.",
      hospitalAdministrators: "Guidance for setting up clinic infrastructure.",
      patients: "More convenient follow-ups.",
      researchers: "Telemedicine efficacy studies."
    },
    impactScores: {
      clinicalPractice: 5,
      medicalEducation: 3,
      research: 2,
      publicHealth: 4,
      hospitalOperations: 4,
      patientCare: 5
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "Specifically addresses Indian telemedicine law."
    },
    peerReviewed: false,
    fundingSource: "IMA",
    coiNote: "None",
    references: [],
    views: 1850,
    seoDescription: "Private clinics in India adopt new telemedicine guidelines for chronic disease management to boost compliance.",
    keywords: ["Private Clinics", "Telemedicine", "IMA Guidelines", "Chronic Care"]
  },
  {
    id: "prov-005",
    slug: "ngos-mobile-cancer-screening-units",
    headline: "Health NGOs Deploy 100+ Mobile Cancer Screening Units in Rural Areas",
    subhead: "Targeting cervical and oral cancers at the grassroots level.",
    category: "Providers",
    specialties: ["Oncology", "Public Health"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-21T09:00:00Z",
    sourcePublishedAt: "2026-07-20T11:30:00Z",
    readingTimeMinutes: 4,
    status: "published",
    sourceName: "Cancer Care Foundation",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.PRESS_RELEASE,
    isAiAssisted: false,
    summary30s: "A coalition of NGOs has launched mobile screening units across five states.",
    summary2min: "To address the late diagnosis of cancers in rural populations, a coalition of Public Health NGOs has deployed over 100 mobile screening units. These vans are equipped for mammography, Pap smears, and oral visual examinations.",
    bodyAnalysis: "### Early Detection\\nThe initiative aims to screen 1 million individuals in 12 months.\\n\\n### Linkage to Care\\nScreen-positive patients are immediately linked to the nearest District Hospital.",
    whyThisMatters: {
      clinicians: "Expect an influx of early-stage referrals.",
      students: "Community oncology principles in action.",
      hospitalAdministrators: "Coordination with NGO referral networks.",
      patients: "Free, accessible screening.",
      researchers: "Data on rural cancer prevalence."
    },
    impactScores: {
      clinicalPractice: 4,
      medicalEducation: 3,
      research: 4,
      publicHealth: 5,
      hospitalOperations: 3,
      patientCare: 5
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "Focused on rural Indian demographics."
    },
    peerReviewed: false,
    fundingSource: "CSR Funds",
    coiNote: "None",
    references: [],
    views: 2900,
    seoDescription: "Health NGOs launch 100+ mobile cancer screening units to combat cervical and oral cancers in rural India.",
    keywords: ["NGOs", "Cancer Screening", "Rural Health", "Public Health Organizations", "Oncology"]
  },
  {
    id: "prov-006",
    slug: "diagnostic-centres-accreditation-mandate",
    headline: "Mandatory NABL Accreditation for All Diagnostic Centres by 2027",
    subhead: "Government cracks down on unregulated pathology labs.",
    category: "Providers",
    specialties: ["Pathology", "Policy"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-20T09:00:00Z",
    sourcePublishedAt: "2026-07-19T11:30:00Z",
    readingTimeMinutes: 5,
    status: "published",
    sourceName: "Ministry of Health",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.GOVERNMENT_NOTIFICATION,
    isAiAssisted: true,
    summary30s: "All pathology labs and diagnostic centres must secure NABL accreditation to operate post-2027.",
    summary2min: "In a sweeping reform to ensure quality control, the Health Ministry has mandated that every diagnostic centre and pathology lab must acquire National Accreditation Board for Testing and Calibration Laboratories (NABL) certification by December 2027.",
    bodyAnalysis: "### Quality Assurance\\nAddresses the issue of erroneous reports from fly-by-night labs.\\n\\n### Financial Burden\\nSmall standalone clinics worry about the high costs of the accreditation process.",
    whyThisMatters: {
      clinicians: "Ensures reliability of diagnostic reports.",
      students: "Understanding laboratory quality standards.",
      hospitalAdministrators: "Must ensure all in-house and partner labs comply.",
      patients: "Guarantees accurate test results.",
      researchers: "Standardized diagnostic data for clinical trials."
    },
    impactScores: {
      clinicalPractice: 5,
      medicalEducation: 2,
      research: 3,
      publicHealth: 4,
      hospitalOperations: 5,
      patientCare: 5
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "Applies to the entire Indian diagnostic sector."
    },
    peerReviewed: false,
    fundingSource: "None",
    coiNote: "None",
    references: [],
    views: 4200,
    seoDescription: "Health Ministry mandates NABL accreditation for all Diagnostic Centres in India by 2027 to ensure quality control.",
    keywords: ["Diagnostic Centres", "NABL", "Pathology Labs", "Healthcare Policy", "Quality Control"]
  },
  {
    id: "prov-007",
    slug: "blood-banks-national-inventory-network",
    headline: "Blood Banks Integrated into National Real-Time Inventory Network",
    subhead: "Eliminating regional shortages through a centralized dashboard.",
    category: "Providers",
    specialties: ["Hematology", "Emergency Medicine"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-19T09:00:00Z",
    sourcePublishedAt: "2026-07-18T11:30:00Z",
    readingTimeMinutes: 3,
    status: "published",
    sourceName: "National Blood Transfusion Council",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.PRESS_RELEASE,
    isAiAssisted: true,
    summary30s: "A new centralized portal connects all licensed blood banks to prevent stockouts.",
    summary2min: "The National Blood Transfusion Council has launched 'e-RaktKosh 2.0', mandating all public and private blood banks to update their inventory of whole blood and components every 6 hours.",
    bodyAnalysis: "### Real-time Tracking\\nHospitals can locate rare blood types instantly.\\n\\n### Wastage Reduction\\nHelps route nearing-expiry components to high-demand zones.",
    whyThisMatters: {
      clinicians: "Faster access to blood for surgeries and trauma.",
      students: "Supply chain management in healthcare.",
      hospitalAdministrators: "Mandatory compliance for in-house blood banks.",
      patients: "Saves critical time during emergencies.",
      researchers: "Data on regional blood demand patterns."
    },
    impactScores: {
      clinicalPractice: 5,
      medicalEducation: 2,
      research: 2,
      publicHealth: 5,
      hospitalOperations: 5,
      patientCare: 5
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "National initiative for India."
    },
    peerReviewed: false,
    fundingSource: "Government",
    coiNote: "None",
    references: [],
    views: 3100,
    seoDescription: "Indian Blood Banks integrated into a national real-time inventory network, e-RaktKosh, to eliminate shortages.",
    keywords: ["Blood Banks", "e-RaktKosh", "Emergency Medicine", "Hematology", "Healthcare Supply Chain"]
  },
  {
    id: "prov-008",
    slug: "district-hospitals-critical-care-blocks",
    headline: "150 District Hospitals Upgraded with 50-Bed Critical Care Blocks",
    subhead: "PM-ABHIM scheme fortifies secondary care infrastructure.",
    category: "Providers",
    specialties: ["Critical Care", "Hospital Operations"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-18T09:00:00Z",
    sourcePublishedAt: "2026-07-17T11:30:00Z",
    readingTimeMinutes: 5,
    status: "published",
    sourceName: "Ministry of Health",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.PRESS_RELEASE,
    isAiAssisted: false,
    summary30s: "Major upgrades to District Hospitals include dedicated critical care and isolation blocks.",
    summary2min: "Under the PM Ayushman Bharat Health Infrastructure Mission, 150 District Hospitals have successfully commissioned new 50-bed Critical Care Blocks equipped with ventilators, dialysis units, and oxygen plants.",
    bodyAnalysis: "### Secondary Care Fortification\\nReduces the burden on tertiary care centers in metro cities.\\n\\n### Pandemic Readiness\\nFeatures negative pressure isolation zones for infectious outbreaks.",
    whyThisMatters: {
      clinicians: "Better facilities to manage severe cases locally.",
      students: "Exposure to critical care at the district level.",
      hospitalAdministrators: "Managing new advanced infrastructure.",
      patients: "Critical care available without traveling to metros.",
      researchers: "Impact evaluation of health infrastructure spending."
    },
    impactScores: {
      clinicalPractice: 4,
      medicalEducation: 3,
      research: 3,
      publicHealth: 5,
      hospitalOperations: 5,
      patientCare: 5
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "Key component of Indian health infrastructure."
    },
    peerReviewed: false,
    fundingSource: "PM-ABHIM",
    coiNote: "None",
    references: [],
    views: 2800,
    seoDescription: "150 District Hospitals in India upgraded with 50-bed Critical Care Blocks under PM-ABHIM to boost secondary care.",
    keywords: ["District Hospitals", "Critical Care", "PM-ABHIM", "Health Infrastructure", "Hospital Upgrades"]
  },
  {
    id: "prov-009",
    slug: "rehabilitation-centres-insurance-coverage",
    headline: "IRDAI Mandates Coverage for Inpatient Rehabilitation Centres",
    subhead: "A major win for stroke, trauma, and post-surgical recovery.",
    category: "Providers",
    specialties: ["Physical Medicine & Rehabilitation", "Policy"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-17T09:00:00Z",
    sourcePublishedAt: "2026-07-16T11:30:00Z",
    readingTimeMinutes: 4,
    status: "published",
    sourceName: "IRDAI",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.GOVERNMENT_NOTIFICATION,
    isAiAssisted: true,
    summary30s: "Health insurance policies must now cover care at certified Rehabilitation Centres.",
    summary2min: "The Insurance Regulatory and Development Authority of India (IRDAI) has issued a directive requiring all comprehensive health insurance policies to cover inpatient stays at certified Rehabilitation Centres for neuro, ortho, and cardiac recovery.",
    bodyAnalysis: "### Broadening Coverage\\nPreviously, insurers rejected claims for non-hospital rehab facilities.\\n\\n### Standardization\\nRehab centres must meet specific medical and paramedical staffing ratios to qualify.",
    whyThisMatters: {
      clinicians: "Can confidently refer patients for specialized inpatient rehab.",
      students: "Growing importance of physiatry.",
      hospitalAdministrators: "Hospitals can partner with standalone rehab centers.",
      patients: "Greatly reduces out-of-pocket expenses for recovery.",
      researchers: "Health economics of comprehensive rehab coverage."
    },
    impactScores: {
      clinicalPractice: 4,
      medicalEducation: 2,
      research: 3,
      publicHealth: 4,
      hospitalOperations: 4,
      patientCare: 5
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "Applies to the Indian health insurance sector."
    },
    peerReviewed: false,
    fundingSource: "None",
    coiNote: "None",
    references: [],
    views: 3900,
    seoDescription: "IRDAI mandates Indian health insurance to cover inpatient Rehabilitation Centres for stroke and trauma recovery.",
    keywords: ["Rehabilitation Centres", "IRDAI", "Health Insurance", "Physical Medicine", "Post-Surgical Recovery"]
  },
  {
    id: "prov-010",
    slug: "community-health-centres-maternal-care-upgrade",
    headline: "Community Health Centres Upgraded with Comprehensive Obstetric Care",
    subhead: "Aiming to bring the Maternal Mortality Rate down to single digits.",
    category: "Providers",
    specialties: ["Obstetrics & Gynecology", "Public Health"],
    region: Region.INDIA,
    imageUrl: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&w=800&q=80",
    imageCredit: "Unsplash",
    imageType: "Editorial",
    publishedAt: "2026-07-16T09:00:00Z",
    sourcePublishedAt: "2026-07-15T11:30:00Z",
    readingTimeMinutes: 5,
    status: "published",
    sourceName: "National Health Mission",
    sourceUrl: "#",
    evidenceLevel: EvidenceLevel.PRESS_RELEASE,
    isAiAssisted: true,
    summary30s: "CHCs are being equipped with 24/7 C-section capabilities and blood storage units.",
    summary2min: "To combat maternal mortality, the National Health Mission has funded the upgrade of 2,000 Community Health Centres (CHCs) to act as First Referral Units (FRUs) with 24/7 comprehensive emergency obstetric and newborn care.",
    bodyAnalysis: "### Emergency Care\\nEnsures that pregnant women in rural areas have access to surgical deliveries within 1 hour.\\n\\n### Staffing\\nDeployment of specialized anesthesiologists and OB/GYNs remains challenging.",
    whyThisMatters: {
      clinicians: "Better facilities for emergency obstetric interventions.",
      students: "Rural postings will offer more hands-on surgical experience.",
      hospitalAdministrators: "Managing specialized resources at the block level.",
      patients: "Lifesaving interventions available closer to home.",
      researchers: "Tracking the impact on Maternal Mortality Ratio (MMR)."
    },
    impactScores: {
      clinicalPractice: 5,
      medicalEducation: 3,
      research: 3,
      publicHealth: 5,
      hospitalOperations: 4,
      patientCare: 5
    },
    indiaRelevance: {
      status: "Directly applicable",
      explanation: "Crucial for India's Sustainable Development Goals (SDG) targets."
    },
    peerReviewed: false,
    fundingSource: "National Health Mission",
    coiNote: "None",
    references: [],
    views: 2600,
    seoDescription: "Community Health Centres in India upgraded with 24/7 comprehensive obstetric care to combat maternal mortality.",
    keywords: ["Community Health Centres", "CHC", "Maternal Health", "Obstetrics", "Public Health", "National Health Mission"]
  }
];
`;

content = content.replace(/];\s*$/, newArticles.trim() + '\n];\n');
fs.writeFileSync(filePath, content, 'utf-8');
console.log('Successfully updated initial_db.ts');
