/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ScientificEvent } from "./types.js";

export const initialEvents: ScientificEvent[] = [
  // LOCAL EVENTS (Priority 1)
  {
    id: "evt-local-001",
    title: "City Hospital Inter-Departmental Grand Rounds: Sepsis Bundle Updates 2026",
    organizer: "Department of Internal Medicine & Critical Care, City Civil Hospital",
    scope: "Local",
    eventType: "Grand Rounds",
    targetProfessions: ["MBBS", "MD/MS", "DM/MCh", "Nursing", "Allied Health Sciences", "Researchers"],
    startDate: "2026-07-28",
    endDate: "2026-07-28",
    duration: "2 Hours (08:00 AM - 10:00 AM IST)",
    venue: "Main Auditorium, Academic Block, City Civil Hospital",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    institution: "City Civil Hospital & Medical College",
    format: "In-Person",
    specialties: ["General Medicine", "Emergency Medicine", "Anaesthesiology", "Infectious Diseases", "Critical Care"],
    cmeCredits: 2,
    cmeAccreditationBody: "Delhi Medical Council (DMC)",
    description: "Bi-weekly departmental case discussion and protocol review focusing on updated Surviving Sepsis Campaign 2026 guidelines, lactate clearance monitoring, and early antibiotic choices in local resistance profiles.",
    objectives: [
      "Review updated 1-hour sepsis resuscitation bundles in high-volume ERs",
      "Analyze antimicrobial stewardship in hospital-acquired multidrug-resistant pathogens",
      "Evaluate point-of-care ultrasound (POCUS) fluid responsiveness in septic shock"
    ],
    registrationDeadline: "2026-07-27",
    cost: "Free for Staff & Residents",
    seatsAvailable: 150,
    seatsLeft: 28,
    isLive: false,
    status: "Approved",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
    keynoteSpeakers: ["Prof. Dr. Rajesh Sharma (HOD Internal Medicine)", "Dr. Meenakshi Sundaram (Critical Care Lead)"],
    speakerProfiles: [
      {
        name: "Prof. Dr. Rajesh Sharma",
        title: "HOD Internal Medicine & Dean Academic Research",
        institution: "City Civil Hospital",
        bio: "Senior clinician with 25+ years in tropical infectious diseases and internal medicine protocol development."
      },
      {
        name: "Dr. Meenakshi Sundaram",
        title: "Lead Intensivist",
        institution: "City Civil Hospital",
        bio: "Pioneer in bedside echocardiography and ECMO protocol standardization in critical care units."
      }
    ],
    schedule: [
      { time: "08:00 AM - 08:30 AM", title: "Case Presentation: Refractory Septic Shock in a Post-Operative Patient", speaker: "Dr. Varun Verma (Senior Resident)" },
      { time: "08:30 AM - 09:15 AM", title: "Keynote: Sepsis 3.0 vs Sepsis 2026 Bundle Changes", speaker: "Prof. Dr. Rajesh Sharma" },
      { time: "09:15 AM - 09:50 AM", title: "Panel Discussion & POCUS Protocol Review", speaker: "Dr. Meenakshi Sundaram & Faculty" },
      { time: "09:50 AM - 10:00 AM", title: "Q&A & CME Attendance Sign-off", speaker: "All Attendees" }
    ],
    contactEmail: "grandrounds@cityhospital.edu.in",
    contactPhone: "+91-11-2345-6789",
    registrationUrl: "https://cityhospital.edu.in/cme/sepsis-2026",
    faqs: [
      { question: "Is registration compulsory for internal house staff?", answer: "Yes, residents must scan their badge at the auditorium entrance for DMC credit recording." },
      { question: "Will slides be uploaded?", answer: "Yes, PDF slides will be accessible on the Healic platform after the session." }
    ],
    aiSummary: {
      executiveSummary: "Detailed review of revised Sepsis-3 bundle application in Indian government tertiary hospital settings. Emphasized targeted antibiotic administration within 60 minutes and restrictive fluid management.",
      keyPearls: [
        "In septic shock, dynamic fluid responsiveness (PLR / VCI collapsibility) prevents fluid overload in 40% of cases.",
        "Procalcitonin-guided antibiotic de-escalation reduces ICU length of stay by 1.8 days.",
        "Empiric coverage must account for local carbapenem-resistant Enterobacterales prevalence."
      ],
      guidelinesDiscussed: ["Surviving Sepsis Campaign 2026 Guidelines", "DMC Antimicrobial Stewardship Charter"],
      researchPapers: ["NEJM 2025 Sepsis Fluid Trial", "Lancet Infectious Diseases Asian Cohort Study"],
      newDrugUpdates: ["Cefiderocol protocol for CRE bacteremia", "Sulbactam-durlobactam in Acinetobacter shock"],
      practiceChangingEvidence: ["Restrictive crystalloid resuscitation (30ml/kg balanced crystalloids max before vasopressor initiation)."]
    },
    hasDownloadableNotes: true,
    viewsCount: 420,
    registrationsCount: 122,
    rating: 4.9
  },
  {
    id: "evt-local-002",
    title: "Regional Hands-on Workshop: Point-of-Care Ultrasound (POCUS) in Emergency & Trauma",
    organizer: "District Medical Association & AIIMS Academic Wing",
    scope: "Local",
    eventType: "Hands-on Training",
    targetProfessions: ["MBBS", "MD/MS", "DM/MCh", "Emergency Medicine", "Radiology", "Physiotherapy"],
    startDate: "2026-08-02",
    endDate: "2026-08-02",
    duration: "1 Day (09:00 AM - 05:00 PM IST)",
    venue: "Simulated Clinical Skill Center, District Medical College, AIIMS Campus",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    institution: "District Medical College / AIIMS",
    format: "In-Person",
    specialties: ["Emergency Medicine", "Radiology", "General Surgery", "Anaesthesiology", "Orthopaedics"],
    cmeCredits: 6,
    cmeAccreditationBody: "State Medical Council",
    description: "Intensive 1-day simulation workshop featuring live human models, eFAST scan protocols, cardiac subxiphoid views, lung ultrasound for pneumothorax, and USG-guided vascular access.",
    objectives: [
      "Master eFAST ultrasound window acquisitions in acute blunt polytrauma",
      "Perform USG-guided internal jugular and femoral vein cannulations safely",
      "Identify pulmonary interstitial syndrome and B-lines in acute decompensated heart failure"
    ],
    abstractDeadline: undefined,
    registrationDeadline: "2026-07-30",
    earlyBirdDeadline: "2026-07-25",
    earlyBirdCost: "₹1,500",
    cost: "₹2,500",
    seatsAvailable: 40,
    seatsLeft: 5,
    isLive: false,
    status: "Approved",
    imageUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80",
    keynoteSpeakers: ["Dr. Sunita Deshmukh (Emergency Sonology Director)", "Dr. Vikramaditya Roy (Trauma Surgery Lead)"],
    schedule: [
      { time: "09:00 AM - 10:30 AM", title: "Physics of Ultrasound & Knobology for Emergency Clinicians", speaker: "Dr. Sunita Deshmukh" },
      { time: "10:30 AM - 01:00 PM", title: "Hands-on Station 1: eFAST Scan & Pneumothorax Identification", speaker: "Faculty Instructors" },
      { time: "02:00 PM - 04:30 PM", title: "Hands-on Station 2: USG Vascular Access & Rapid Echo", speaker: "Dr. Vikramaditya Roy" },
      { time: "04:30 PM - 05:00 PM", title: "OSCE Assessment & Certification", speaker: "All Mentors" }
    ],
    contactEmail: "pocus2026@dma-health.org",
    registrationUrl: "https://dma-health.org/pocus-workshop-2026",
    hasDownloadableNotes: true,
    viewsCount: 680,
    registrationsCount: 35,
    rating: 4.8
  },

  // NATIONWIDE EVENTS (Priority 2)
  {
    id: "evt-national-001",
    title: "APICON 2027 - 82nd Annual Conference of Association of Physicians of India",
    organizer: "Association of Physicians of India (API)",
    scope: "Nationwide",
    eventType: "Conference",
    targetProfessions: ["MBBS", "MD/MS", "DM/MCh", "Medical Education", "Researchers", "Public Health"],
    startDate: "2027-02-18",
    endDate: "2027-02-21",
    duration: "4 Days",
    venue: "Jio World Convention Centre, BKC",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    institution: "Association of Physicians of India",
    format: "In-Person",
    specialties: ["General Medicine", "Cardiology", "Endocrinology", "Infectious Diseases", "Nephrology", "Pulmonology"],
    cmeCredits: 16,
    cmeAccreditationBody: "Maharashtra Medical Council (MMC) & Medical Council of India",
    description: "The largest annual gathering of physicians across India, featuring 200+ scientific sessions, clinical guideline transitions for South Asian populations, drug innovation symposia, and national paper awards.",
    objectives: [
      "Implement revised ICMR guidelines for early Type 2 Diabetes reversal and GLP-1/GIP receptor agonist prescribing",
      "Review national tuberculosis elimination chemotherapy shortened regimens (BPaLM/BPaL)",
      "Explore artificial intelligence integration in primary care clinical decision support systems"
    ],
    abstractDeadline: "2026-11-30",
    registrationDeadline: "2027-01-15",
    earlyBirdDeadline: "2026-10-31",
    earlyBirdCost: "₹5,000",
    cost: "₹6,500 / $180",
    seatsAvailable: 3500,
    seatsLeft: 640,
    isLive: false,
    status: "Approved",
    imageUrl: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=800&q=80",
    keynoteSpeakers: ["Prof. Dr. V. Mohan (Madras Diabetes Research Foundation)", "Dr. Soumya Swaminathan (Former Chief Scientist, WHO)", "Dr. Randeep Guleria (Former Director, AIIMS New Delhi)"],
    schedule: [
      { time: "Day 1 - 09:00 AM", title: "Plenary: Cardiometabolic Risk in South Asians - What 2026 Trials Reveal", speaker: "Prof. Dr. V. Mohan" },
      { time: "Day 2 - 11:00 AM", title: "Oration: TB Elimination by 2030 - Operational Challenges and Solutions", speaker: "Dr. Soumya Swaminathan" },
      { time: "Day 3 - 02:00 PM", title: "Debate: SGLT2i vs SGLT1/2 Dual Inhibitors in Non-Diabetic Heart Failure", speaker: "National Faculty Panel" }
    ],
    contactEmail: "secretariat@apicon2027.com",
    organizerWebsite: "https://www.apicon2027.com",
    registrationUrl: "https://www.apicon2027.com/register",
    hasDownloadableNotes: true,
    viewsCount: 3420,
    registrationsCount: 2860,
    rating: 4.95
  },
  {
    id: "evt-national-002",
    title: "National CME on Pediatric Vaccinology & Maternal Immunization",
    organizer: "Indian Academy of Pediatrics (IAP)",
    scope: "Nationwide",
    eventType: "CME",
    targetProfessions: ["MBBS", "MD/MS", "DM/MCh", "Nursing", "Public Health"],
    startDate: "2026-11-07",
    endDate: "2026-11-08",
    duration: "2 Days",
    venue: "Hotel Taj Palace",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    institution: "Indian Academy of Pediatrics",
    format: "In-Person",
    specialties: ["Pediatrics", "Infectious Diseases", "Obstetrics & Gynecology", "Community Medicine", "General Medicine"],
    cmeCredits: 8,
    cmeAccreditationBody: "Delhi Medical Council (DMC)",
    description: "An intensive updates course covering new Quadrivalent Influenza schedules, pneumococcal conjugate vaccine (PCV15) national clinical trial data, and evidence-based safety profiles of RSV maternal vaccines.",
    abstractDeadline: "2026-09-15",
    registrationDeadline: "2026-10-25",
    earlyBirdDeadline: "2026-09-01",
    earlyBirdCost: "₹1,500",
    cost: "₹2,200",
    seatsAvailable: 500,
    seatsLeft: 110,
    isLive: false,
    status: "Approved",
    imageUrl: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80",
    keynoteSpeakers: ["Dr. Gagandeep Kang (Vellore Christian Medical College)", "Prof. Dr. G.V. Satyavati (Senior Pediatric Consultant)"],
    contactEmail: "vaccinology2026@iapindia.org",
    registrationUrl: "https://www.iapindia.org/cme-vaccinology-2026",
    hasDownloadableNotes: true,
    viewsCount: 1890,
    registrationsCount: 390,
    rating: 4.75
  },
  {
    id: "evt-national-003",
    title: "AI in Clinical Medicine & Radiology Symposium (AICMRS 2026)",
    organizer: "Indian Society of Radiology & HealthTech Innovation Hub",
    scope: "Nationwide",
    eventType: "AI in Medicine Event",
    targetProfessions: ["MBBS", "MD/MS", "DM/MCh", "Radiology", "Researchers", "Health Technology"],
    startDate: "2026-09-19",
    endDate: "2026-09-20",
    duration: "2 Days",
    venue: "NIMHANS Convention Centre",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    institution: "Indian Society of Radiology",
    format: "Hybrid",
    specialties: ["Radiology", "Oncology", "Neurology", "Cardiology", "Pathology", "General Medicine"],
    cmeCredits: 10,
    cmeAccreditationBody: "Karnataka Medical Council (KMC)",
    description: "Cutting-edge national summit focusing on FDA/CDSCO approved deep-learning models for lung nodule detection, AI-guided echocardiography, automated CT stroke perfusion triage, and ethical framework integration.",
    objectives: [
      "Evaluate clinical diagnostic accuracy of AI triage tools in acute intracranial hemorrhage CT scans",
      "Integrate large vision-language models into draft radiology reporting workflows",
      "Understand medicolegal liability and CDSCO Class C software medical device regulations"
    ],
    abstractDeadline: "2026-08-10",
    registrationDeadline: "2026-09-10",
    cost: "Virtual: ₹1,200 / In-person: ₹3,500",
    seatsAvailable: 800,
    seatsLeft: 145,
    isLive: false,
    status: "Approved",
    imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
    keynoteSpeakers: ["Dr. Harsh Mahajan (Mahajan Imaging & IRS)", "Prof. Dr. V. R. Kulkarni (IISc Bioengineering)"],
    registrationUrl: "https://radiology-ai.org.in/summit2026",
    hasDownloadableNotes: true,
    viewsCount: 2150,
    registrationsCount: 655,
    rating: 4.9
  },

  // INTERNATIONAL EVENTS (Priority 3)
  {
    id: "evt-intl-001",
    title: "Global Cardiology Summit 2026: Heart Failure & SGLT2i Advances",
    organizer: "European Society of Cardiology (ESC) & International Cardiac Research Society",
    scope: "International",
    eventType: "Conference",
    targetProfessions: ["MBBS", "MD/MS", "DM/MCh", "Researchers"],
    startDate: "2026-10-12",
    endDate: "2026-10-14",
    duration: "3 Days",
    venue: "Boston Convention Center & Global Online Portal",
    city: "Boston",
    state: "MA",
    country: "United States",
    institution: "European Society of Cardiology / Harvard Medical",
    format: "Hybrid",
    specialties: ["Cardiology", "General Medicine", "Pharmacology", "Nephrology", "Endocrinology"],
    cmeCredits: 18,
    cmeAccreditationBody: "EACCME / AMA PRA Category 1",
    description: "Deep dive into breakthrough therapeutics in heart failure with preserved ejection fraction (HFpEF), next-generation SGLT2 inhibitor trials, cardiorenal protection mechanisms, and AI-driven structural echo imaging.",
    objectives: [
      "Analyze multi-center randomized controlled trials evaluating SGLT2i + ARNI triple therapy in HFpEF",
      "Assess myocardial fibrosis quantification using contrast-enhanced 3T cardiac MRI",
      "Understand transatlantic guideline concordances in acute decompensated heart failure management"
    ],
    abstractDeadline: "2026-08-15",
    registrationDeadline: "2026-09-30",
    earlyBirdDeadline: "2026-08-01",
    earlyBirdCost: "$150 Virtual / $400 Physical",
    cost: "Virtual: $200 / Physical: $550 (Free for PG Residents)",
    seatsAvailable: 5000,
    seatsLeft: 1200,
    isLive: false,
    status: "Approved",
    imageUrl: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=800&q=80",
    keynoteSpeakers: ["Dr. Eugene Braunwald (Harvard Medical School)", "Dr. Valentin Fuster (Mount Sinai Hospital, NY)", "Prof. Barbara Casadei (University of Oxford)"],
    contactEmail: "congress@globalcardiology2026.org",
    organizerWebsite: "https://www.globalcardiology2026.org",
    registrationUrl: "https://www.globalcardiology2026.org/register",
    hasDownloadableNotes: true,
    viewsCount: 4890,
    registrationsCount: 3800,
    rating: 4.96
  },
  {
    id: "evt-intl-002",
    title: "WHO High-Level Global Symposium on Tuberculosis & Drug Resistance Elimination",
    organizer: "World Health Organization (WHO) Global TB Programme",
    scope: "International",
    eventType: "Symposium",
    targetProfessions: ["MBBS", "MD/MS", "DM/MCh", "Public Health", "Researchers", "Nursing"],
    startDate: "2026-09-05",
    endDate: "2026-09-05",
    duration: "1 Day (Simulcast in 6 Languages)",
    venue: "WHO Headquarters Main Auditorium & Global Livestream",
    city: "Geneva",
    country: "Switzerland",
    institution: "World Health Organization",
    format: "Online",
    specialties: ["Infectious Diseases", "Pulmonology", "Public Health", "Community Medicine", "Pharmacology"],
    cmeCredits: 4,
    cmeAccreditationBody: "WHO Continuing Medical Education Board",
    description: "An international consensus forum discussing global rollout of shortened 4-month chemotherapy regimens (HPZM) for drug-susceptible pulmonary TB and 6-month BPaLM regimen for MDR/RR-TB.",
    objectives: [
      "Implement country-level BPaLM regimen transition frameworks with active drug safety monitoring (aDSM)",
      "Evaluate digital adherence technologies (smart pillboxes and video-observed therapy)",
      "Review WHO operational guidance on contact tracing and preventive treatment with 3HP/1HP"
    ],
    registrationDeadline: "2026-09-04",
    cost: "Free Open Access (Mandatory Registration)",
    isLive: false,
    status: "Approved",
    imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80",
    keynoteSpeakers: ["Dr. Tedros Adhanom Ghebreyesus (Director-General, WHO)", "Dr. Tereza Kasaeva (Director, WHO Global TB Programme)"],
    organizerWebsite: "https://www.who.int/events/tb-symposium-2026",
    registrationUrl: "https://www.who.int/events/tb-symposium-2026/register",
    hasDownloadableNotes: true,
    viewsCount: 6200,
    registrationsCount: 5100,
    rating: 4.92
  },
  {
    id: "evt-intl-003",
    title: "Stanford Medicine Summit: Clinician-Aligned AI in Diagnostics & Patient Care",
    organizer: "Stanford University School of Medicine & AIMI Center",
    scope: "International",
    eventType: "Conference",
    targetProfessions: ["MBBS", "MD/MS", "DM/MCh", "Researchers", "Health Technology", "Medical Education"],
    startDate: "2026-12-03",
    endDate: "2026-12-04",
    duration: "2 Days",
    venue: "Li Ka Shing Center, Stanford University & Online Stream",
    city: "Stanford",
    state: "CA",
    country: "United States",
    institution: "Stanford School of Medicine",
    format: "Hybrid",
    specialties: ["Health Technology", "General Medicine", "Radiology", "Oncology", "Pathology", "Medical Education"],
    cmeCredits: 12,
    cmeAccreditationBody: "ACCME (Stanford CME)",
    description: "A prestigious global masterclass assessing generative AI models for automated electronic health record chart reviews, multi-modal diagnostic reasoning models, and physician-in-the-loop safety benchmarks.",
    objectives: [
      "Review clinical validation standards for ambient AI scribe technologies in outpatient clinics",
      "Analyze multi-modal AI systems integrating histopathology slides and genomic sequencing",
      "Establish institutional governance committees for AI model bias and hallucination mitigation"
    ],
    abstractDeadline: "2026-10-01",
    registrationDeadline: "2026-11-20",
    cost: "Virtual: $150 / In-Person: $480",
    seatsAvailable: 2000,
    seatsLeft: 310,
    isLive: false,
    status: "Approved",
    imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80",
    keynoteSpeakers: ["Dr. Fei-Fei Li (Co-Director, Stanford HAI)", "Dr. Eric Topol (Founder & Director, Scripps Research)", "Dr. Nigam Shah (Chief Data Scientist, Stanford Health Care)"],
    registrationUrl: "https://med.stanford.edu/ai-summit-2026",
    hasDownloadableNotes: true,
    viewsCount: 5400,
    registrationsCount: 1690,
    rating: 4.98
  }
];
